/**
 * Emit `public/prepaint.js` from `src/lib/axes.json`, on every dev start and every build.
 *
 * Why a generator rather than a hand-written script: the ten axes must be applied to <html>
 * BEFORE the first paint, which rules out a module script (deferred) and therefore rules out
 * importing the registry at runtime. The alternative to generating is retyping the table in a
 * second file, and a second table drifts - that is exactly the failure the one-table rule
 * exists to prevent. So the table stays in one place and this writes the pre-paint copy from it.
 *
 * It moved here from `scripts/gen-prepaint.mjs` (TASK-019, 2026-09-26: the house rules forbid a
 * scripts folder), in the site's own shape (`windowsweep-web/vite.config.ts`, `prepaintPlugin`).
 * The output is byte-identical to that script's except the header line naming this file.
 *
 * 🔴 The committed copy is still a gate. The build rewrites `public/prepaint.js` before anything
 * reads it, so the shipped file cannot drift; `desktop-ci.yml` then runs
 * `git diff --exit-code -- public/prepaint.js`, which fails when the committed copy was stale -
 * an `axes.json` change committed without the file it generates.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Plugin } from 'vite';

interface AxisValue {
  value: string;
}
interface Axis {
  key: string;
  attr: string;
  def: string;
  values: AxisValue[];
}
interface AxisRegistry {
  storageKey: string;
  axes: Axis[];
}

/** The pre-paint script `axes.json` produces, and how many axes it carries. */
export interface RenderedPrepaint {
  script: string;
  axes: number;
}

/**
 * Render the pre-paint script from the axis registry.
 *
 * @param root - the desktop app's root (the folder holding `src/` and `public/`).
 */
export function renderPrepaint(root: string): RenderedPrepaint {
  const registry = JSON.parse(
    readFileSync(join(root, 'src/lib/axes.json'), 'utf8')
  ) as AxisRegistry;
  const payload = JSON.stringify({
    storageKey: registry.storageKey,
    axes: registry.axes.map((a) => ({
      key: a.key,
      attr: a.attr,
      def: a.def,
      values: a.values.map((v) => v.value),
    })),
  });

  const script = `/* GENERATED by vite/prepaint.ts from src/lib/axes.json - do not edit.
   Loaded synchronously from <head>, so the axis pass runs before the body is
   parsed and therefore before first paint. Appearance applied late is a colour
   flash; density or text size applied late is a reflow. */
(function () {
  'use strict';
  var R = ${payload};
  var prefs = {};
  try {
    var raw = localStorage.getItem(R.storageKey);
    if (raw) { var p = JSON.parse(raw); prefs = (p && typeof p === 'object' && 'v' in p) ? (p.v || {}) : (p || {}); }
  } catch (e) { prefs = {}; }

  var url = {};
  try {
    var q = new URLSearchParams(location.search);
    R.axes.forEach(function (a) {
      var v = q.get(a.key);
      if (v && a.values.indexOf(v) !== -1) url[a.key] = v;   // shown, never persisted
    });
  } catch (e) { /* ignore */ }

  function value(a) {
    if (a.key in url) return url[a.key];
    var v = prefs[a.key];
    return a.values.indexOf(v) !== -1 ? v : a.def;
  }

  var el = document.documentElement;
  var appearance = 'dark';
  R.axes.forEach(function (a) {
    var v = value(a);
    el.setAttribute(a.attr, v);
    if (a.key === 'theme') {
      if (v === 'system') {
        try { appearance = matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark'; }
        catch (e) { appearance = 'dark'; }
      } else { appearance = v; }
    }
  });
  el.setAttribute('data-appearance', appearance);
  el.style.colorScheme = appearance;
  window.__wsPrepaintAxes = R.axes.length;
})();
`;
  return { script, axes: registry.axes.length };
}

/**
 * The Vite plugin: write `public/prepaint.js` when it differs from what `axes.json` renders.
 * It runs once the config is resolved - before the dev server serves `public/` and before a
 * build copies it into `dist/` - and writes nothing when the file already matches.
 *
 * @param root - the desktop app's root.
 */
export function prepaintPlugin(root: string): Plugin {
  return {
    name: 'windowsweep-desktop:prepaint',
    configResolved(config) {
      const { script, axes } = renderPrepaint(root);
      const out = join(root, 'public/prepaint.js');
      if (existsSync(out) && readFileSync(out, 'utf8') === script) {
        config.logger.info(
          `[prepaint] public/prepaint.js matches axes.json (${String(axes)} axes)`
        );
        return;
      }
      writeFileSync(out, script);
      config.logger.info(`[prepaint] wrote public/prepaint.js from ${String(axes)} axes`);
    },
  };
}
